### ISSUE TITLE
error: Bad source: /home/mockbuild/rpmbuild/SOURCES/init-ceph.in-fedora.patch: No such file or directory

### ISSUE THREAD

**Issue by devicenull** [brandt/ceph-infernalis-centos-6-rpm#1]
My attempts to build his were failing with:

Step 18 : VOLUME /artifacts
 ---> Running in 83620273547a
 ---> 754db02677db
Removing intermediate container 83620273547a
Successfully built 754db02677db
docker run --rm -it -v `pwd`/artifacts:/artifacts brandt/ceph-rpm bash ./build.sh
error: Bad source: /home/mockbuild/rpmbuild/SOURCES/init-ceph.in-fedora.patch: No such file or directory
make: **\* [pkg] Error 1

I grabbed this file from the Ceph repo, and dropped it in rpmbuild/SOURCES, which seems to have resolved the issue: https://raw.githubusercontent.com/ceph/ceph/master/rpm/init-ceph.in-fedora.patch

**Comment by brandt** [comment]
My bad.  I had intended on committing that patch, but my `.gitignore` was excluding it.  It's fixed now.

Thanks for reporting it!
